/* ACTION TYPE CONSTANTS BELOW */

// Auth
export const AUTH_ERROR = "AUTH_ERROR";

export const USER_REQUESTED = "USER_REQUESTED";
export const USER_LOADED = "USER_LOADED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const DEREGISTER_SUCCESS = "DEREGISTER_SUCCESS";
export const DEREGISTER_FAILED = "DEREGISTER_FAILED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const EMAIL_TOKEN_SENT = "EMAIL_TOKEN_SENT";
export const EMAIL_TOKEN_ERROR = "EMAIL_TOKEN_ERROR";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";

export const PASSWORD_TOKEN_SENT = "PASSWORD_TOKEN_SENT";
export const PASSWORD_TOKEN_ERROR = "PASSWORD_TOKEN_ERROR";
export const PASSWORD_TOKEN_VERIFIED = "PASSWORD_TOKEN_VERIFIED";

// Errors
export const ERRORS_RETURNED = "ERRORS_RETURNED";
export const ERRORS_LOGGED = "ERRORS_LOGGED";
export const ERRORS_CLEARED = "ERRORS_CLEARED";

// Routes
export const ROUTES_REQUESTED = "ROUTES_REQUESTED";
export const ROUTES_ERROR = "ROUTES_ERROR";
export const ROUTE_CREATED = "ROUTE_CREATED";
export const ROUTES_FETCHED = "ROUTES_FETCHED";
export const ROUTE_READ = "ROUTE_READ";
export const ROUTE_UPDATED = "ROUTE_UPDATED";
export const ROUTE_DELETED = "ROUTE_DELETED";

// Runs
export const RUNS_REQUESTED = "RUNS_REQUESTED";
export const RUNS_ERROR = "RUNS_ERROR";
export const RUN_CREATED = "RUN_CREATED";
export const RUNS_FETCHED = "RUNS_FETCHED";
export const RUN_READ = "RUN_READ";
export const RUN_UPDATED = "RUN_UPDATED";
export const RUN_DELETED = "RUN_DELETED";

// Friends
export const FRIENDS_REQUESTED = "FRIENDS_REQUESTED";
export const FRIENDS_ERROR = "FRIENDS_ERROR";
export const FRIENDS_FETCHED = "FRIENDS_FETCHED";
export const FRIEND_ADDED = "FRIEND_ADDED";
export const FRIEND_READ = "FRIEND_READ";
export const FRIEND_ACCEPTED = "FRIEND_ACCEPTED"
export const FRIEND_DELETED = "FRIEND_DELETED";